/** Portfolio descriptions grounded in the existing schematic images.
 * Values identify design intent, not measured hardware performance.
 */
export const circuitStudies = [
  {
    id: "antoniou-gic",
    width: 1021,
    height: 562,
    title: "Antoniou GIC",
    type: "Active-inductor study",
    image: "/assets/gic-schematic.webp",
    mobileImage: "/assets/gic-schematic-mobile.webp",
    href: "/projects/circuits#antoniou-gic",
    alt: "Antoniou grounded-inductor schematic with two TL072 op-amps and an AC sweep setup",
    result: "10 H design target",
    description: "An active circuit targeting the behaviour of a large grounded inductor. The study makes the ideal target and practical op-amp limits explicit.",
    purpose: "Explore how an active impedance-converter circuit can represent a large inductance without using a physical 10 H coil.",
    approach: "The schematic combines two TL072 op-amps with a resistor-capacitor network. It specifies a 10 H ideal target and a 10 Hz–100 kHz AC sweep, using a test current source to examine the input impedance.",
    evidence: "The available schematic records the topology, component values, supply rails and AC-analysis setup. Its annotation flags a model resonance; the response plot and native simulation files are not included in this case study.",
    limitation: "10 H is a design target, not a measured inductance. The schematic alone does not establish a usable bandwidth, stability margin or agreement with hardware.",
    nextCheck: "Compare simulated impedance magnitude and phase with the ideal inductive response, then identify the frequency range in which the model is a useful approximation.",
  },
  {
    id: "khn-filter",
    width: 1021,
    height: 562,
    title: "KHN State-Variable Filter",
    type: "Filter topology & debugging",
    image: "/assets/svf-schematic.webp",
    mobileImage: "/assets/svf-schematic-mobile.webp",
    href: "/projects/circuits#khn-filter",
    alt: "Three-op-amp KHN filter schematic with high-pass, band-pass and low-pass outputs and a feedback sign warning",
    result: "Feedback sign issue identified",
    description: "A three-output filter study with a documented feedback-sign problem. The case study explains the intended response and why stability must be checked separately.",
    purpose: "Study a filter architecture that exposes high-pass, band-pass and low-pass outputs from a shared signal path.",
    approach: "The drawing separates a summing stage from two integrators and labels the feedback paths. This makes it possible to follow how the output signals return to the summer and inspect their signs.",
    evidence: "The schematic explicitly notes that its shown feedback sign gives negative damping. That issue is retained here as a debugging finding, not presented as a corrected or validated filter.",
    limitation: "The shown design has a documented stability issue. A frequency-response setup is not proof of stable time-domain behaviour, and no corrected implementation is claimed here.",
    nextCheck: "Resolve the feedback-sign issue, then compare the intended transfer functions with both AC response and transient behaviour before making performance claims.",
  },
  {
    id: "instrumentation-amplifier",
    width: 1017,
    height: 564,
    title: "Instrumentation Amplifier",
    type: "Differential signal conditioning",
    image: "/assets/instrumentation-amplifier.webp",
    mobileImage: "/assets/instrumentation-amplifier-mobile.webp",
    href: "/projects/circuits#instrumentation-amplifier",
    alt: "Three-TL072 instrumentation amplifier schematic with an input gain stage and a unity difference stage",
    result: "Three-op-amp topology",
    description: "A differential-amplifier study separating the input gain stage from the difference stage, with explicit component values and an AC test setup.",
    purpose: "Explore a signal-conditioning circuit intended to amplify the difference between two inputs rather than treating either input as the complete signal.",
    approach: "Two TL072 stages form the input section and a third forms the difference amplifier. The drawing labels the gain-setting network, opposite-phase input sources and ±15 V supplies.",
    evidence: "The schematic includes a 1 Hz–100 kHz AC sweep setup. It makes the two-stage architecture and resistor relationships inspectable, but does not provide measured noise, offset or common-mode rejection results.",
    limitation: "The configured small-signal AC analysis does not establish output headroom or large-signal behaviour. No precision, common-mode rejection or real sensor-interface performance is claimed.",
    nextCheck: "Check differential and common-mode gain separately, examine resistor-tolerance sensitivity, and verify operating range and clipping with an appropriate transient test.",
  },
  {
    id: "pfd-charge-pump",
    width: 1448,
    height: 1086,
    title: "PFD + Charge Pump",
    type: "Mixed-signal concept",
    image: "/assets/pfd-charge-pump.webp",
    mobileImage: "/assets/pfd-charge-pump-mobile.webp",
    href: "/projects/circuits#pfd-charge-pump",
    alt: "Concept diagram separating reference clocks, phase-frequency detector logic and a nominal 100 microamp charge pump",
    result: "100 μA nominal current sources",
    description: "A block-level study of how reference and feedback clock timing drives an analogue charge-pump output. The diagram separates the digital and analogue functions.",
    purpose: "Explain the interface between clock-comparison logic and the charge-pump output used as a building block in a phase-locked loop.",
    approach: "The diagram groups reference and feedback clocks, two flip-flops with reset logic, and switched current sources labelled 100 μA. UP and DN labels connect the logic and analogue sections.",
    evidence: "The available evidence is a concept diagram. It describes the functional blocks; it is not a transistor-level implementation, a simulation waveform or a complete phase-locked loop.",
    limitation: "The nominal current labels do not establish current matching, dead-zone behaviour, jitter, output compliance or loop lock. Those results have not been demonstrated in this case study.",
    nextCheck: "Specify the clock and reset timing, exercise leading and lagging inputs in simulation, and evaluate charge-pump behaviour before connecting it to a complete loop.",
  },
  {
    id: "boost-converter",
    width: 1448,
    height: 1086,
    title: "Boost Converter",
    type: "Power-stage concept",
    image: "/assets/boost-converter-qucs.webp",
    mobileImage: "/assets/boost-converter-qucs-mobile.webp",
    href: "/projects/circuits#boost-converter",
    alt: "12 volt boost-converter concept with a 100 microhenry inductor, controlled switch, Schottky diode, capacitor and load",
    result: "12 V input · open-loop concept",
    description: "A step-up power-stage study showing the inductor, switch, rectifier and output network. It separates the proposed topology from unverified output performance.",
    purpose: "Study the elements of a switching power stage intended to produce an output voltage above its input.",
    approach: "The diagram specifies a 12 V source, a 100 μH inductor, a controlled switch, a 1N5819 Schottky diode, a 100 μF capacitor and a 50 Ω load. A PWM source drives the switch; no feedback-regulation loop is shown.",
    evidence: "The diagram identifies the power-stage components and connections. It does not include switching waveforms, a defined duty cycle or measured output results.",
    limitation: "This is an open-loop concept, not a validated power supply. Output voltage, ripple, efficiency, component stresses and thermal limits remain unverified.",
    nextCheck: "Define switching conditions and device models, then evaluate startup, inductor current, output ripple and component ratings across the intended load range.",
  },
] as const;
